jobs:
  include:
    - stage: test
      language: node_js
      if: type = push AND (NOT (branch = master))
      node_js: 12
      install:
        - npm i
      script:
        - npm run test
      cache:
        directories:
          - 'node_modules'
      notifications:
        email: false

    - stage: sonarqube
      if: branch = master and type IN (pull_request, push)
      language: node_js
      node_js: 12
      install:
        - npm install -g sonarqube-scanner
      script:
        - npm run test:cov
        - bash travis/sonar.sh

    - stage: build and deploy
      language: node_js
      if: type IN (pull_request, push) AND branch = master
      node_js: 12
      install:
        - npm i
      script:
        - npm run test
        - npm run build
      cache:
        directories:
          - 'node_modules'
      notifications:
        email: false
      deploy:
        - provider: npm
          email: 'r.heinen@nanogiants.de'
          api_key: $NPM_TOKEN
          skip_cleanup: true
          on:
            type: push
